### ISSUE TITLE
"headers" always empty

### ISSUE THREAD

**Issue by EmadAlblueshi** [vert-x3/vertx-tcp-eventbus-bridge#11]
### Version

* vert.x core: 3.2.1
* vert.x tcp eventbus bridge: 3.2.1

### Context

The tcp eventbus bridge always returns empty "headers" 

#### Socket client (input) :

```javascript
{
  "type" : "send",
  "headers" : {
    "action" : "findAll"
  },
  "body" : {
    "model" : "news"
  },
  "address" : "io.vertx",
  "replyAddress" : "io.vertx"
}
```

#### Socket client (output) :

```javascript
{
  "type" : "message",
  "address" : "io.vertx",
  "headers" : { },
  "body" : {
    "model" : "news"
  }
}
```

**Comment by pmlopes** [comment]
Can you verify if the 3.0.0-SNAPSHOT is fixed?

We merged a PR a few days ago related to message headers:

https://github.com/vert-x3/vertx-tcp-eventbus-bridge/pull/8

**Comment by EmadAlblueshi** [comment]
@pmlopes The `Message<JsonObject>` has the headers but I did not get the output

**Comment by EmadAlblueshi** [comment]
@pmlopes The `Message<JsonObject>` in 3.3.0-SNAPSHOT has the headers but I did not get the output as in  3.2.1. Here you are what I did to test both versions :

```javascript
JsonObject headers = new JsonObject();
headers.put("action", "findAll");

JsonObject body = new JsonObject();
body.put("model", "news");

JsonObject protocol = new JsonObject();
protocol.put("type", "send");
protocol.put("headers", headers);
protocol.put("body", body);
protocol.put("address", "io.vertx");
protocol.put("replyAddress", "io.vertx");


Buffer buffer = Buffer.buffer();
buffer.appendInt(protocol.encode().getBytes().length);
buffer.appendString(protocol.encode());

Socket clientSocket = new Socket("localhost", 7000);

DataOutputStream output = new DataOutputStream(clientSocket.getOutputStream());
output.write(buffer.getBytes());

DataInputStream input = new DataInputStream(clientSocket.getInputStream());

int bytesLength = input.readInt();
byte[] bytes = new byte[bytesLength];
for(int i = 0; i < bytesLength; i++) {
  bytes[i] = input.readByte();
}

input.close();
output.close();
clientSocket.close();

Buffer result = Buffer.buffer(bytes);
System.out.println(result.toJsonObject().encodePrettily());
```

**Comment by pmlopes** [comment]
@EmadAlblueshi what do you mean by did not get the output as expected?

**Comment by EmadAlblueshi** [comment]
@pmlopes The tcp eventbus bridge has received the request but does not reply

**Comment by pmlopes** [comment]
I've added your reproducer to the test suite and fixed the code. Your reproducer shown 2 issues, first replies were broken and second one reply id collision was not handled properly.
