### ISSUE TITLE
Replying to a message triggers an access_denied error

### ISSUE THREAD

**Issue by bramdrenthe** [vert-x3/vertx-tcp-eventbus-bridge#14]
### Version

* vert.x core: 3.3.3
* vert.x tcp eventbus bridge: 3.3.3

### Context

When replying to a message sent over the bridge, an "access_denied" error is triggered. The (generated) ReplyAddress is not contained in the InboundsPermitted list, which is the only list that is checked in the checkMatches function.

### Proposed fix

Either add reply-addresses to the InboundsPermitted list (probably not desired), or let the checkMatches function also check the "replies" map, something like:

    private void handler(NetSocket socket) {
        // ...
            switch (type) {
                case "send":
                    if (checkMatches(true, address, replies)) {
        // ...

    private boolean checkMatches(boolean inbound, String address) { return checkMatches(inbound, address, null); }

    private boolean checkMatches(boolean inbound, String address, Map<String, Message<JsonObject>> replies) {
        if (replies != null && inbound && replies.containsKey(address)) return true;
        // ...

**Comment by tobias** [comment]
Any chance of getting this fixed? I'm tripping over this as well. If the above solution seems amenable, I'm happy to provide a PR.

**Comment by pmlopes** [comment]
@tobias could you confirm that #17 solves your issue?

**Comment by tobias** [comment]
Thanks for the prompt fix @pmlopes. I had to do a bit more to get it to work properly, please see #18.

**Comment by tobias** [comment]
@pmlopes any estimate as to when you'll get a chance to look at this?

**Comment by tobias** [comment]
Thanks!
