### ISSUE TITLE
Should sends be differentiated from publishes?

### ISSUE THREAD

**Issue by tobias** [vert-x3/vertx-tcp-eventbus-bridge#20]
Currently, the bridge makes no differentiation between incoming messages sent via `send()` and messages sent via `publish()`. They both arrive on the client side of the bridge with a `type` of `message`, so the client has no way to know which type the message is. For bridge clients that allow multiple handlers to be registered on the same address (mimicking the behavior of Vert.x proper), the send/publish semantics can't be honored (unless the message also includes a `replyAddress` - in that case, we can assume it is a send).

Is it by intent that the message doesn't include this information? If not, would you be amenable to adding an additional field in the message to convey the message type?

**Comment by vietj** [comment]
it's a bug imho

**Comment by tobias** [comment]
Is there a way currently in Vert.x to detect when a message was sent vs published? I see that `MessageImpl` has a public `send()` method for that, but it isn't exposed by the `Message` interface.

**Comment by tobias** [comment]
Any updates/thoughts on this? I'm happy to implement this in the bridge if there is a way for me to tell a `Message` is a send.

**Comment by tobias** [comment]
Ping - any thoughts on this? Or is there a more appropriate place to discuss it?

**Comment by pmlopes** [comment]
I'm not sure if it is a bug. The eventbus message object: http://vertx.io/docs/apidocs/io/vertx/core/eventbus/Message.html does not differentiate sends from publishes, it is assumed that if a message has a reply address then it is a `send` if not it is a `publish` this heuristic falls for all bridges since some translation needs to happen at the bridge side and the addresses are relative to the bridge.

**Comment by pmlopes** [comment]
Touching the code to add what kind of message is being delivered will probably not just affect the tcp bridge but core and sockjs bridge too. Is this something desired?

**Comment by tsegismont** [comment]
Couldn't that be just an additional flag on the message object?

2016-12-12 17:25 GMT+01:00 Paulo Lopes <notifications@github.com>:

**Comment by pmlopes** [comment]
What would be the use case of such flag? Yes I know you could see if it was a send or a publish but why would you need to handle them differently?

Both on vert.x core and bridges you can define a consumer for an address and the messages delivered at that consumer are undistinguished if they are coming from a send or a publish. One cannot just say register on address only for published messages not send ones.

So this is why I'm saying it is not a bug per se, but probably something that could be enhanced. I'd just like to know a good use case for such feature.

**Comment by tsegismont** [comment]
Got you, thanks for the details

2016-12-13 10:02 GMT+01:00 Paulo Lopes <notifications@github.com>:

**Comment by tobias** [comment]
The use-case that led me to report this issue is with a bridge client that allows registering multiple consumers for the same address. When a message crosses the bridge to the client, the only way the client can tell if the message is a send (and therefore should only be delivered to one of the consumers) is if it has a reply address. If the message was a send, but has no reply address, the client cannot differentiate it from a publish, so can't know that it should only be delivered to one consumer. So if you want the bridge client to have the same send/publish semantics as core, I think you have to signal sends by some method.

**Comment by pmlopes** [comment]
@tobias yes I'd like to have the same semantics across the whole eventbus so there is no confusion for the end user. In this case I think this should first happen on core and then added to the bridges.
