### ISSUE TITLE
how to retry connect / Reconnect 

### ISSUE THREAD

**Issue by k-mooijman** [vert-x3/vertx-tcp-eventbus-bridge#27]
What is the recommended way to retry connection or reconnect on connection fail ?

**Comment by tsegismont** [comment]
Can you ask your question on the Vert.x user forum? Not everyone in the
community is subscribed to the GitHub repositories.

See vertx.io/community

2017-05-02 22:15 GMT+02:00 k-mooijman <notifications@github.com>:
