### ISSUE TITLE
ping messages return unknown_type

### ISSUE THREAD

**Issue by nfranke** [vert-x3/vertx-tcp-eventbus-bridge#37]
### Version

* vert.x core: 3.5.1
* vert.x tcp eventbus bridge:3 .5.1

### Context

When clients send a "ping" message, the server responds with an error "unknwon_type"

### Steps to reproduce

1. client sends "ping" command
2. server returns error

### Extra

In TcpEventBusBridgeImpl.java in the method: private void handler(NetSocket socket) the code is as follows:

```
      checkCallHook(() -> new BridgeEventImpl(eventType, msg, socket),
        () -> {
          if (eventType == BridgeEventType.SOCKET_PING) {
            // No specific action
          } else if (address == null) {
            sendErrFrame("missing_address", socket);
            log.error("msg does not have address: " + msg.toString());
            return;
          }
          doSendOrPub(true, socket, address, msg, registry, replies);
        },
        () -> {
          sendErrFrame("blocked by bridgeEvent handler", socket);
        });
```

Perhaps the call to doSendOrPub(true, socket, address, msg, registry, replies) should be wrapped in an:

```
} else {
    doSendOrPub(true, socket, address, msg, registry, replies);
}
```

In this case eventType == BridgeEventType.SOCKET_PING is true, but it still does the doSendOrPub

**Comment by pmlopes** [comment]
This looks like a bug where the pong response is missing.

**Comment by vietj** [comment]
can you make a fix for 3.5.2 ?

**Comment by gaol** [comment]
@vietj @pmlopes  I made up a PR for this issue, would you please review? Thanks.

**Comment by pmlopes** [comment]
The pr has been merged!
