### ISSUE TITLE
doc : add event type `ping`

### ISSUE THREAD

**Issue by javathought** [vert-x3/vertx-tcp-eventbus-bridge#41]
### Version

* vert.x core: 3.5.3
* vert.x tcp eventbus bridge: 3.5.3

### Context

On documentation (example on https://vertx.io/docs/vertx-tcp-eventbus-bridge/java/) : 
The `ping` event type is not present in the doc : 
- ping is not documented (and thus pong is not present in the list of types sent back to the client)

**Comment by javathought** [comment]
Updated as part was a duplicate of #34 .

**Comment by javathought** [comment]
ping issue  is closed (#37 )

**Comment by gaol** [comment]
I think this can be closed because both `ping` and `pong` are in doc now. :)
