### ISSUE TITLE
RECIPIENT_FAILURE missing for bridge client consumers

### ISSUE THREAD

**Issue by wem** [vert-x3/vertx-tcp-eventbus-bridge#44]
### Version

* vert.x core: 3.6.0.CR1
* vert.x tcp eventbus bridge: 3.6.0.CR1

Missing common event bus failure handling for consumers placed on bridge clients. There is no way to get a ReplyException on a server-side sender in the case of a recipient failure on a bridge client consumer.

**Comment by EddieParis** [comment]
Hi ! I have same issue, I made a slight protocol modification, i.e. to fail a message, you have to make a regular 'send' command but if the field 'failureCode' is present the TCPEventBusBridge code will fail the message. Pushed on my fork, I'll issue a pull request after some friend's review even if it is light touch modifications.

**Comment by vngantk** [comment]
I have this problem too. I have reviewed @EddieParis' pull request, and it looks fine to me. When will it be merged and available for release?

**Comment by vietj** [comment]
@vngantk it should be in 3.7

**Comment by vietj** [comment]
sorry for late reply @wem

**Comment by wem** [comment]
Hi
No problem, it would be nice when this will be part of 3.7 and so an "official way" is there.

**Comment by vietj** [comment]
yes it shall be
